---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helinyilmaz

resources:
  - deployment-lab4.yaml
  - deployment-redis.yaml
  - deployment-project.yaml
  - service-lab4.yaml
  - service-redis.yaml
  - service-project.yaml