---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helinyilmaz

resources:
  - ./namespace.yaml
  - ../../base

patches:
  - path: service-lab4-lb.yaml
    target:
      kind: Service
      labelSelector: app=lab-prediction-service
# added
images:
  - name: lab
    newName: lab
    newTag: "latest"